"!!ARBvp1.0\n"
"# cgc version 3.1.0013, build date Apr 18 2012\n"
"# command line args: -profile arbvp1 -oglsl\n"
"# source file: vsalias.glsl\n"
"#vendor NVIDIA Corporation\n"
"#version 3.1.0.13\n"
"#profile arbvp1\n"
"#program main\n"
"#semantic gl_ModelViewProjectionMatrix : state.matrix.mvp.transpose\n"
"#semantic gl_ModelViewMatrix : state.matrix.modelview.transpose\n"
"#semantic Blend\n"
"#semantic ShadeVector\n"
"#semantic LightColor\n"
"#var float4 gl_TexCoord[0] : $vout.TEX0 : TEX0 : -1 : 1\n"
"#var float4 gl_TexCoord[1] : $vout.TEX1 : TEX1 : -1 : 1\n"
"#var float4 gl_TexCoord[2] :  :  : -1 : 0\n"
"#var float4 gl_TexCoord[3] :  :  : -1 : 0\n"
"#var float4 gl_TexCoord[4] :  :  : -1 : 0\n"
"#var float4 gl_TexCoord[5] :  :  : -1 : 0\n"
"#var float4 gl_TexCoord[6] :  :  : -1 : 0\n"
"#var float4 gl_TexCoord[7] :  :  : -1 : 0\n"
"#var float4 gl_MultiTexCoord0 : $vin.TEXCOORD0 : TEXCOORD0 : -1 : 1\n"
"#var float4 gl_Position : $vout.POSITION : HPOS : -1 : 1\n"
"#var float4x4 gl_ModelViewProjectionMatrix : state.matrix.mvp.transpose : c[1], 4 : -1 : 1\n"
"#var float4 gl_FrontColor : $vout.COLOR0 : COL0 : -1 : 1\n"
"#var float4x4 gl_ModelViewMatrix : state.matrix.modelview.transpose : c[5], 4 : -1 : 1\n"
"#var float gl_FogFragCoord : $vout.FOGC : FOGC : -1 : 1\n"
"#var float Blend :  : c[9] : -1 : 1\n"
"#var float3 ShadeVector :  : c[10] : -1 : 1\n"
"#var float4 LightColor :  : c[11] : -1 : 1\n"
"#var float4 Pose1Vert : $vin.ATTR0 : ATTR0 : -1 : 1\n"
"#var float3 Pose1Normal : $vin.ATTR1 : ATTR1 : -1 : 1\n"
"#var float4 Pose2Vert : $vin.ATTR2 : ATTR2 : -1 : 1\n"
"#var float3 Pose2Normal : $vin.ATTR3 : ATTR3 : -1 : 1\n"
"#const c[0] = 0.29545453 1 0\n"
"PARAM c[12] = { { 0.29545453, 1, 0 },\n"
"state.matrix.mvp.transpose.row[0..3],\n"
"state.matrix.modelview.transpose.row[0..3],\n"
"program.local[9..11] };\n"
"TEMP R0;\n"
"TEMP R1;\n"
"TEMP R2;\n"
"MOV R0, vertex.attrib[0];\n"
"ADD R0, vertex.attrib[2], -R0;\n"
"MAD R0, R0, c[9].x, vertex.attrib[0];\n"
"MUL R1, R0.y, c[2];\n"
"MAD R1, R0.x, c[1], R1;\n"
"MAD R1, R0.z, c[3], R1;\n"
"MUL R2.x, R0.y, c[6].z;\n"
"MAD R0.y, R0.x, c[5].z, R2.x;\n"
"MAD R0.x, R0.z, c[7].z, R0.y;\n"
"MAD R0.x, R0.w, c[8].z, R0;\n"
"ABS result.fogcoord.x, R0;\n"
"DP3 R0.x, vertex.attrib[1], c[10];\n"
"SLT R0.y, R0.x, c[0].z;\n"
"MAD R0.z, R0.x, c[0].x, c[0].y;\n"
"ADD R0.x, R0, -R0.z;\n"
"ABS R0.y, R0;\n"
"MAD result.position, R0.w, c[4], R1;\n"
"SGE R0.w, c[0].z, R0.y;\n"
"ADD R0.x, R0, c[0].y;\n"
"MAD R0.x, R0, R0.w, R0.z;\n"
"DP3 R0.y, vertex.attrib[3], c[10];\n"
"SLT R0.w, R0.y, c[0].z;\n"
"MAD R0.z, R0.y, c[0].x, c[0].y;\n"
"ADD R0.y, R0, -R0.z;\n"
"ABS R0.w, R0;\n"
"SGE R0.w, c[0].z, R0;\n"
"ADD R0.y, R0, c[0];\n"
"MAD R0.y, R0, R0.w, R0.z;\n"
"ADD R0.y, R0, -R0.x;\n"
"MOV R0.w, c[0].y;\n"
"MAD R0.xyz, R0.y, c[9].x, R0.x;\n"
"MOV result.texcoord[0], vertex.texcoord[0];\n"
"MOV result.texcoord[1], vertex.texcoord[0];\n"
"MUL result.color, R0, c[11];\n"
"END\n"
"# 34 instructions, 3 R-regs\n"
